app:
  name: 'Effective Mobile'
  version: '1.0.0'

database:
  host: "100.96.10.3"
  port: 5432
  dbname: "subscription"
  username: "user"
  password: "user"

http_server:
  host: "100.96.10.2"
  port: 5015
  timeout: 4s
  idle_timeout: 30s

logger:
  level: "INFO"