app:
  name: 'Effective Mobile'
  version: '1.0.0'

database:
  host: "127.0.0.1"
  port: 5432
  dbname: "subscription_testing"
  username: "user"
  password: "user"

http_server:
  host: "127.0.0.1"
  port: 8082
  timeout: 4s
  idle_timeout: 30s

logger:
  level: "INFO"